### ISSUE TITLE
Recaptcha v2 not working in registration form

### ISSUE THREAD

**Issue by majky90** [bpato/simplerecaptcha#3]
Hello,
In registration form recaptcha v2 and v2 invisible not working. Other form working good. If i choose v2 checkbox registration work without check recaptcha and in v2 invisible captcha not working registration not created and show error in cosole. Can you help me solve this problem? I use recaptcha v2 checkbox in newslatter in every sites and in autcontroller use v2 invisible.

Uncaught Error: grecaptcha.execute only works with invisible reCAPTCHA.
    at recaptcha__sk.js:374
    at HTMLFormElement.<anonymous> (prihlasit-sa?create_account=1:1960)
    at HTMLFormElement.dispatch (bottom-54e569435.js:39)
    at HTMLFormElement.g.handle (bottom-54e569435.js:39)
(anonymous) @ recaptcha__sk.js:374
(anonymous) @ prihlasit-sa?create_account=1:1960
dispatch @ bottom-54e569435.js:39
g.handle @ bottom-54e569435.js:39

**Comment by bpato** [comment]
Hi, I will check it, have you tried the development version of the develop branch?

**Comment by bpato** [comment]
Hi @majky90

I have published an update, i tested it with the last version of prestashop and work fine. 
Please, check if your error persists.
